version: '3'

tasks:
  emacs-cpp:
    desc: "Emacs in a C/C++ development environment"
    cmds:
      - nix develop .#cpp --command emacs -nw
  emacs-python:
    desc: "Emacs in a Python development environment"
    cmds:
      - nix develop .#python --command emacs -nw
