version: '3'

tasks:
  emacs:
    desc: "Start emacs built from this flake headless"
    cmds:
      - $(nix build .#emacs-nox --print-out-paths)/bin/emacs
  emacs-cpp:
    desc: "Emacs in a C/C++ development environment"
    cmds:
      - nix develop .#cpp --command emacs
  emacs-python:
    desc: "Emacs in a Python development environment"
    cmds:
      - nix develop .#python --command emacs
